# Main JPA datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/HsmManager
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Quartz configuration

spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=never
spring.quartz.jdbc.schema=classpath:quartz-data.sql

spring.quartz.properties.org.quartz.scheduler.instanceName=quartz-scheduler
spring.quartz.properties.org.quartz.scheduler.instanceId=AUTO
spring.quartz.properties.org.quartz.scheduler.instanceIdGenerator.class=com.QuartzDemo.CustomQuartzInstanceIdGenerator

spring.quartz.properties.org.quartz.threadPool.threadCount=20

#spring.quartz.properties.org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
#spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate
spring.quartz.properties.org.quartz.jobStore.useProperties=true
spring.quartz.properties.org.quartz.jobStore.misfireThreshold=60000
spring.quartz.properties.org.quartz.jobStore.tablePrefix=QRTZ_
spring.quartz.properties.org.quartz.jobStore.isClustered=true
#spring.quartz.properties.org.quartz.jobStore.dataSource=myDS
#spring.quartz.properties.org.quartz.dataSource.myDS.connectionProvider.class=org.springframework.scheduling.quartz.SpringConnectionProvider


spring.quartz.properties.org.quartz.plugin.shutdownHook.class=org.quartz.plugins.management.ShutdownHookPlugin
spring.quartz.properties.org.quartz.plugin.shutdownHook.cleanShutdown=TRUE

spring.main.allow-bean-definition-overriding=true

server.tomcat.max-http-header-size=65536

quartz.job.jobA.cronexpression=0 0/5 * * * * ?


